send_message:
  name: Send message
  description: Send a text message to a MeshCore node by name or public key.
  fields:
    node_id:
      name: Node ID
      description: The name of the node to send the message to.
      required: false
      example: "node1"
      selector:
        text:
    pubkey_prefix:
      name: Public Key Prefix
      description: The public key prefix (at least 6 characters) of the node to send the message to.
      required: false
      example: "f293ac"
      selector:
        text:
    message:
      name: Message
      description: The message to send.
      required: true
      example: "Hello from Home Assistant!"
      selector:
        text:
    entry_id:
      name: Config Entry ID
      description: The config entry ID if you have multiple MeshCore devices. Leave empty to use the first available device.
      required: false
      example: "abc123def456"
      selector:
        text:

send_channel_message:
  name: Send channel message
  description: Send a text message to a MeshCore public channel.
  fields:
    channel_idx:
      name: Channel Index
      description: The index number of the channel to send to.
      required: true
      example: 0
      selector:
        number:
          min: 0
          max: 255
          mode: box
    message:
      name: Message
      description: The message to send to the channel.
      required: true
      example: "Hello from Home Assistant!"
      selector:
        text:
    entry_id:
      name: Config Entry ID
      description: The config entry ID if you have multiple MeshCore devices. Leave empty to use the first available device.
      required: false
      example: "abc123def456"
      selector:
        text: