send_message:
  name: Send message
  description: Send a text message to a MeshCore node by name or public key.
  fields:
    node_id:
      name: Node ID
      description: The name of the node to send the message to.
      required: false
      example: "node1"
      selector:
        text:
    pubkey_prefix:
      name: Public Key Prefix
      description: The public key prefix (at least 6 characters) of the node to send the message to.
      required: false
      example: "f293ac"
      selector:
        text:
    message:
      name: Message
      description: The message to send.
      required: true
      example: "Hello from Home Assistant!"
      selector:
        text:
    entry_id:
      name: Config Entry ID
      description: The config entry ID if you have multiple MeshCore devices. Leave empty to use the first available device.
      required: false
      example: "abc123def456"
      selector:
        text:

send_channel_message:
  name: Send channel message
  description: Send a text message to a MeshCore public channel.
  fields:
    channel_idx:
      name: Channel Index
      description: The index number of the channel to send to.
      required: true
      example: 0
      selector:
        number:
          min: 0
          max: 255
          mode: box
    message:
      name: Message
      description: The message to send to the channel.
      required: true
      example: "Hello from Home Assistant!"
      selector:
        text:
    entry_id:
      name: Config Entry ID
      description: The config entry ID if you have multiple MeshCore devices. Leave empty to use the first available device.
      required: false
      example: "abc123def456"
      selector:
        text:

send_ui_message:
  name: Send UI Message
  description: >-
    Send a message using the MeshCore UI helpers. This service reads values from
    'select.meshcore_recipient_type', 'select.meshcore_channel', 'select.meshcore_contact',
    and 'text.meshcore_message' to determine the recipient and message content.
    Call this service directly from a button card for a seamless messaging interface.
  fields:
    entry_id:
      name: Config Entry ID
      description: The config entry ID if you have multiple MeshCore devices. Leave empty to use the first available device.
      required: false
      example: "abc123def456"
      selector:
        text:

execute_cli_command_ui:
  name: Execute CLI Command from UI
  description: >-
    Execute a CLI command using the text.meshcore_cli_command helper entity.
    This service reads the command from the text helper and executes it.
    It will automatically clear the input field after execution.
  fields:
    entry_id:
      name: Config Entry ID
      description: The config entry ID if you have multiple MeshCore devices. Leave empty to use the first available device.
      required: false
      example: "abc123def456"
      selector:
        text:

cli_command:
  name: Send CLI command
  description: >-
    Send an arbitrary CLI command directly to the MeshCore node. This is an advanced feature
    that provides direct access to the underlying CLI interface.
    CAUTION: Commands like 'set_txpower', 'set_name', 'set_radio', 'reboot', etc. will 
    make PERMANENT CHANGES to your node's configuration. Use with care.
  fields:
    command:
      name: Command
      description: >-
        The CLI command to send to the node.
        examples: advert, change_path <ct> <path>, set_name <n>, sync_time, etc.
      required: true
      example: "advert"
      selector:
        text:
    entry_id:
      name: Config Entry ID
      description: The config entry ID if you have multiple MeshCore devices. Leave empty to use the first available device.
      required: false
      example: "abc123def456"
      selector:
        text: